var LocalizedStrings = require('./LocalizedStrings');

var strings = new  LocalizedStrings({
    "en":{
      //无用
      OpenAJK:"Open Aijiakang",
      AboutBloodPressure:"About the blood pressure monitor",

      //设置页内容
      重命名:"ReName",
      设备共享:"Equipment Sharing",
      检查固件更新:"Check Firmware Updates",
      解除连接:"Remove Connection",
      更多:"More",
      编辑:"Edit",
      完成:"Complete",
      RevokeTheTermsOfUseAndPrivacyPolicyAuthorization:"Revoke The Terms Of Use And Privacy Policy Authorization",
      撤销授权后设备会与您当前登陆的账号解除绑定并清除该设备之前存储在服务端的数据物理设备中存储的数据需要您进行人工本地物理重置后清除若设备支持您可以直接在设备上进行重置或参照隐私政策中的撤销授权进行重置上述数据撤销后均不可恢复若要重新使用设备需要您再次进行绑定并且重新授权
      :'After the authorization is revoked, the device will be unbound with the account you are currently logged in and the data stored on the server before the device is purged, and the data stored in the physical device will need to be purged after manual local physical reset, and if the device supports it, you can reset it directly on the device or refer to the revocation authorization in   "Privacy None of the above data can be recovered after it is revoked, and to reuse the device, you need to bind again and re-authorize it.', 

      DearRemind:"Dear Remind",
      AccessWeChat:"Access WeChat",
      DeviceInformation:"Device Information",
      Help:"Help",
      UniversalSettings:"Universal Settings",
      AgreementAndPolicy:"Agreement And Policy",
      ServiceAgreement:"Service Agreement",
      PrivacyPolicy:"Privacy Policy",
      BootScreen:"Boot Screen",

      MeasurementResultsVoiceBroadcast: "Voice announcements of the results",
      BatteryPower:"Battery level",
      SerialNumber:"Serial NO",
      FirmwareVersion:"Version of the firmwares",
      PluginVersion:"Version of the plug-in",

      BPUsingInstructions:"BP Using Instructions",
      BPFaq:"BP FAQ",

      WhenTheBloodPressureMonitorOn:"BP monitor online, you will receive message",
      MON:"MON",
      TUE:"TUE",
      WED:"WED",
      THU:"THU",
      FRI:"FRI",
      SAT:"SAT",
      SUN:"SUN",
      MomAndDadRemind:"Mom and Dad, remember to stick to the blood pressure!",

      iHealthBloodPressureMonitor:" iHealth BP Monitor",
      ShareWeChat:"Share blood pressure to WeChat's two-dimensional code to relatives and friends, to facilitate real-time attention to your friends and relatives of blood pressure changes!",
      SharetoWeChatfriends:"Share WeChat",

      Setting:"Setting",

      //主页面
      UserFBloodPressure:"1 blood pressure",
      DadsBloodPressure:"User1 blood pressure",
      UserMBloodPressure:"2 blood pressure",
      MothersBloodPressure:"User2 blood pressure",
      Findmore:"Find More",
      ResultsOfNormalBloodPressure:"Normal BP results(times)",
      HighBloodPressureResults:"High BP results(times)",
      HighVoltageHighestValue:"High BP Maximum",
      LowVoltageHighestValue:"Low BP Maximum",
      BloodPressureMean:"Average BP",
      MeanValueOfPulsePressure:"Average pressure",
      Normal:" Normal ",
      High:" High ",
      Low:" Low ",
      BloodPressureOutcomeDetails:"Detail Results",
      AccordingToWHO:"The WHO blood pressure standards your result is:",
      SevereHypertension:"Severe hypertension",
      ModerateHypertension:"Moderate Hypertension",
      MildHypertension:"Mild hypertension",
      NormalPartialHypertension:"Normal partial high blood pressure",
      NormalBloodPressure:"Normal blood pressure",
      IdealBloodPressure:"The ideal blood pressure",
      HighPressure:"SYS",
      LowPressure:"DIA",
      HeartRate:"HR",
      TimesPerMinute:"Times/Min",
      InterpretationOfBloodPressureResults:"Blood pressure results interpretation",
      HowDoYouFeelBeforeYouMeasure:"[mood]:How do you feel before the measurement?",
      Good:"Good",
      Commonly:"General",
      Bad:"Bad",
      TakingAntihypertensiveDrugsWithin2Hours:"[medication]:Did you take the antihypertensive drug within 2 hours?",
      Yes:"Yes",
      No:"No",
      LoadLatestMeasurementRecord:"Loading the latest measurement record",
      LoadingHistoryRecord:"Loading the history measurement record",
      Loading:"Loading",

      nian:"/",
      yue:"/",
      ri:"",
    },
    "zh-Hans-CN":{
      //简体中文 iOS9+
      //无用
      OpenAJK:"打开爱家康",
      AboutBloodPressure:"关于血压计",

      //设置页内容
      重命名:"重命名",
      设备共享:"设备共享",
      检查固件更新:"检查固件更新",
      解除连接:"解除连接",
      更多:"更多",
      编辑:"编辑",
      完成:"完成",
      RevokeTheTermsOfUseAndPrivacyPolicyAuthorization:"撤销\"使用条款和隐私政策\"授权",
      撤销授权后设备会与您当前登陆的账号解除绑定并清除该设备之前存储在服务端的数据物理设备中存储的数据需要您进行人工本地物理重置后清除若设备支持您可以直接在设备上进行重置或参照隐私政策中的撤销授权进行重置上述数据撤销后均不可恢复若要重新使用设备需要您再次进行绑定并且重新授权
      :'撤销授权后，设备会与您当前登陆的账号解除绑定并清除该设备之前存储在服务端的数据；物理设备中存储的数据需要您进行人工本地物理重置后清除，若设备支持，您可以直接在设备上进行重置或参照\"隐私政策\"中的撤销授权进行重置，上述数据撤销后均不可恢复，若要重新使用设备，需要您再次进行绑定并且重新授权', 
      

      DearRemind:"宝贝提醒",
      AccessWeChat:"接入微信",
      DeviceInformation:"设备信息",
      Help:"帮助",
      UniversalSettings:"通用设置",
      AgreementAndPolicy:"服务协议和隐私政策",
      ServiceAgreement:"服务协议",
      PrivacyPolicy:"隐私政策",
      BootScreen:"血压计开机画面",

      MeasurementResultsVoiceBroadcast: "测量结果语音播报",
      BatteryPower:"电池电量",
      SerialNumber:"序列号",
      FirmwareVersion:"固件版本号",
      PluginVersion:"插件版本",

      BPUsingInstructions:"使用说明",
      BPFaq:"常见问题",

      WhenTheBloodPressureMonitorOn:"当血压计开机时，将收到默认留言",
      MON:"周一",
      TUE:"周二",
      WED:"周三",
      THU:"周四",
      FRI:"周五",
      SAT:"周六",
      SUN:"周日",
      MomAndDadRemind:"爸爸妈妈，记得坚持测血压!",

      iHealthBloodPressureMonitor:" iHealth智控血压",
      ShareWeChat:"分享血压计二维码给微信亲友，方便亲友实时关注您的血压变化",
      SharetoWeChatfriends:"分享至微信好友",

      Setting:"设置",

      //主页面
      DadsBloodPressure:"用户1 测的血压",
      MothersBloodPressure:"用户2 测的血压",
      UserFBloodPressure:"1 测的血压",
      UserMBloodPressure:"2 测的血压",
      Findmore:"发现更多",
      ResultsOfNormalBloodPressure:"正常血压结果(次)",
      HighBloodPressureResults:"偏高血压结果(次)",
      HighVoltageHighestValue:"高压最高值(mmHg)",
      LowVoltageHighestValue:"低压最高值(mmHg)",
      BloodPressureMean:"血压平均值(mmHg)",
      MeanValueOfPulsePressure:"脉压平均值(mmHg)",
      Normal:" 正常 ",
      High:" 偏高 ",
      Low:" 偏低 ",
      BloodPressureOutcomeDetails:"血压结果详情",
      AccordingToWHO:"根据WHO世界卫生组织血压标准评定您本次测量为：",
      SevereHypertension:"重度高血压",
      ModerateHypertension:"中度高血压",
      MildHypertension:"轻度高血压",
      NormalPartialHypertension:"正常偏高血压",
      NormalBloodPressure:"正常血压",
      IdealBloodPressure:"理想血压",
      HighPressure:"高压",
      LowPressure:"低压",
      HeartRate:"心率",
      TimesPerMinute:"次/分钟",
      InterpretationOfBloodPressureResults:"血压结果解读",
      HowDoYouFeelBeforeYouMeasure:"【心情】:测量前的心情感觉如何？",
      Good:"好",
      Commonly:"一般",
      Bad:"不好",
      TakingAntihypertensiveDrugsWithin2Hours:"【服药】:2小时内服用过降压药吗？",
      Yes:"有",
      No:"没有",
      LoadLatestMeasurementRecord:"加载最新测量记录",
      LoadingHistoryRecord:"加载历史测量记录",
      Loading:"加载中",

      nian:"年",
      yue:"月",
      ri:"日",
    },
    "zh-Hant-CN":{
      //繁体中文 iOS9+
      //无用
      OpenAJK:"打開愛家康",
      AboutBloodPressure:"关于血压计",

      //设置页内容
      重命名:"重命名",
      设备共享:"设备共享",
      检查固件更新:"检查固件更新",
      解除连接:"解除连接",
      更多:"更多",
      编辑:"编辑",
      完成:"完成",
      RevokeTheTermsOfUseAndPrivacyPolicyAuthorization:"撤销\"使用条款和隐私政策\"授权",


      DearRemind:"寶貝提醒",
      AccessWeChat:"接入微信",
      DeviceInformation:"设备信息",
      Help:"帮助",
      UniversalSettings:"通用设置",
      AgreementAndPolicy:"服务协议和隐私政策",
      ServiceAgreement:"服务协议",
      PrivacyPolicy:"隐私政策",
      BootScreen:"血压计开机画面",

      MeasurementResultsVoiceBroadcast: "測量結果語音播報",
      BatteryPower:"電池電量",
      SerialNumber:"序列號",
      FirmwareVersion:"固件版本號",
      PluginVersion:"插件版本",

      BPUsingInstructions:"使用說明",
      BPFaq:"常見問題",

      WhenTheBloodPressureMonitorOn:"當血壓計開機時，將收到默認留言",
      MON:"周一",
      TUE:"周二",
      WED:"周三",
      THU:"周四",
      FRI:"周五",
      SAT:"周六",
      SUN:"周日",
      MomAndDadRemind:"爸爸媽媽，記得堅持測血壓！",

      iHealthBloodPressureMonitor:" iHealth智控血壓",
      ShareWeChat:"分享血壓計二維碼給微信親友，方便親友實时關注您的血壓變化",
      SharetoWeChatfriends:"分享至微信好友",

      Setting:"設置",

      //主页面
      DadsBloodPressure:"用戶1 測的血壓",
      MothersBloodPressure:"用戶2 測的血壓",
      UserFBloodPressure:"1 測的血壓",
      UserMBloodPressure:"2 測的血壓",
      Findmore:"發現更多",
      ResultsOfNormalBloodPressure:"正常血壓結果(次)",
      HighBloodPressureResults:"偏高血壓結果(次)",
      HighVoltageHighestValue:"高壓最高值(mmHg)",
      LowVoltageHighestValue:"低壓最高值(mmHg)",
      BloodPressureMean:"血壓平均值(mmHg)",
      MeanValueOfPulsePressure:"脈壓平均值(mmHg)",
      Normal:" 正常 ",
      High:" 偏高 ",
      Low:" 偏低 ",
      BloodPressureOutcomeDetails:"血壓結果詳情",
      AccordingToWHO:"根據WHO世界衛生組織血壓標準評定您本次測量為：",
      SevereHypertension:"重度高血壓",
      ModerateHypertension:"中度高血壓",
      MildHypertension:"輕度高血壓",
      NormalPartialHypertension:"正常偏高血壓",
      NormalBloodPressure:"正常血壓",
      IdealBloodPressure:"理想血壓",
      HighPressure:"高壓",
      LowPressure:"低壓",
      HeartRate:"心率",
      TimesPerMinute:"次/分鐘",
      InterpretationOfBloodPressureResults:"血壓結果解讀",
      HowDoYouFeelBeforeYouMeasure:"【心情】:測量前的心情感覺如何？",
      Good:"好",
      Commonly:"一般",
      Bad:"不好",
      TakingAntihypertensiveDrugsWithin2Hours:"【服藥】：2小時內服用過降壓藥嗎？",
      Yes:"有",
      No:"没有",
      LoadLatestMeasurementRecord:"加載最新測量記錄",
      LoadingHistoryRecord:"加載歷史測量記錄",
      Loading:"加載中",

      nian:"年",
      yue:"月",
      ri:"日",
    },
    "zh-Hans":{
      //简体中文 iOS7,8
      //无用
      OpenAJK:"打开爱家康",
      AboutBloodPressure:"关于血压计",

      //设置页内容

      重命名:"重命名",
      设备共享:"设备共享",
      检查固件更新:"检查固件更新",
      解除连接:"解除连接",
      更多:"更多",
      编辑:"编辑",
      完成:"完成",
      RevokeTheTermsOfUseAndPrivacyPolicyAuthorization:"撤销\"使用条款和隐私政策\"授权",

     

      DearRemind:"宝贝提醒",
      AccessWeChat:"接入微信",
      DeviceInformation:"设备信息",
      Help:"帮助",
      UniversalSettings:"通用设置",
      BootScreen:"血压计开机画面",
      AgreementAndPolicy:"服务协议和隐私政策",
      ServiceAgreement:"服务协议",
      PrivacyPolicy:"隐私政策",
      MeasurementResultsVoiceBroadcast: "测量结果语音播报",
      BatteryPower:"电池电量",
      SerialNumber:"序列号",
      FirmwareVersion:"固件版本号",
      PluginVersion:"插件版本",

      BPUsingInstructions:"使用说明",
      BPFaq:"常见问题",

      WhenTheBloodPressureMonitorOn:"当血压计开机时，将收到默认留言",
      MON:"周一",
      TUE:"周二",
      WED:"周三",
      THU:"周四",
      FRI:"周五",
      SAT:"周六",
      SUN:"周日",
      MomAndDadRemind:"爸爸妈妈，记得坚持测血压!",

      iHealthBloodPressureMonitor:" iHealth智控血压",
      ShareWeChat:"分享血压计二维码给微信亲友，方便亲友实时关注您的血压变化",
      SharetoWeChatfriends:"分享至微信好友",

      Setting:"设置",

      //主页面
      DadsBloodPressure:"用户1 测的血压",
      MothersBloodPressure:"用户2 测的血压",
      UserFBloodPressure:"1 测的血压",
      UserMBloodPressure:"2 测的血压",
      Findmore:"发现更多",
      ResultsOfNormalBloodPressure:"正常血压结果(次)",
      HighBloodPressureResults:"偏高血压结果(次)",
      HighVoltageHighestValue:"高压最高值(mmHg)",
      LowVoltageHighestValue:"低压最高值(mmHg)",
      BloodPressureMean:"血压平均值(mmHg)",
      MeanValueOfPulsePressure:"脉压平均值(mmHg)",
      Normal:" 正常 ",
      High:" 偏高 ",
      Low:" 偏低 ",
      BloodPressureOutcomeDetails:"血压结果详情",
      AccordingToWHO:"根据WHO世界卫生组织血压标准评定您本次测量为：",
      SevereHypertension:"重度高血压",
      ModerateHypertension:"中度高血压",
      MildHypertension:"轻度高血压",
      NormalPartialHypertension:"正常偏高血压",
      NormalBloodPressure:"正常血压",
      IdealBloodPressure:"理想血压",
      HighPressure:"高压",
      LowPressure:"低压",
      HeartRate:"心率",
      TimesPerMinute:"次/分钟",
      InterpretationOfBloodPressureResults:"血压结果解读",
      HowDoYouFeelBeforeYouMeasure:"【心情】:测量前的心情感觉如何？",
      Good:"好",
      Commonly:"一般",
      Bad:"不好",
      TakingAntihypertensiveDrugsWithin2Hours:"【服药】:2小时内服用过降压药吗？",
      Yes:"有",
      No:"没有",
      LoadLatestMeasurementRecord:"加载最新测量记录",
      LoadingHistoryRecord:"加载历史测量记录",
      Loading:"加载中",

      nian:"年",
      yue:"月",
      ri:"日",
    },
    "zh-Hant":{
      //繁体中文 iOS7,8
      //无用
      OpenAJK:"打開愛家康",
      AboutBloodPressure:"关于血压计",

      //设置页内容
      重命名:"重命名",
      设备共享:"设备共享",
      检查固件更新:"检查固件更新",
      解除连接:"解除连接",
      更多:"更多",
      编辑:"编辑",
      完成:"完成",
      RevokeTheTermsOfUseAndPrivacyPolicyAuthorization:"撤销\"使用条款和隐私政策\"授权",


      DearRemind:"寶貝提醒",
      AccessWeChat:"接入微信",
      DeviceInformation:"设备信息",
      Help:"帮助",
      UniversalSettings:"通用设置",
      BootScreen:"血压计开机画面",
      AgreementAndPolicy:"服务协议和隐私政策",
      ServiceAgreement:"服务协议",
      PrivacyPolicy:"隐私政策",
      MeasurementResultsVoiceBroadcast: "測量結果語音播報",
      BatteryPower:"電池電量",
      SerialNumber:"序列號",
      FirmwareVersion:"固件版本號",
      PluginVersion:"插件版本",

      BPUsingInstructions:"使用說明",
      BPFaq:"常見問題",

      WhenTheBloodPressureMonitorOn:"當血壓計開機時，將收到默認留言",
      MON:"周一",
      TUE:"周二",
      WED:"周三",
      THU:"周四",
      FRI:"周五",
      SAT:"周六",
      SUN:"周日",
      MomAndDadRemind:"爸爸媽媽，記得堅持測血壓！",

      iHealthBloodPressureMonitor:" iHealth智控血壓",
      ShareWeChat:"分享血壓計二維碼給微信親友，方便親友實时關注您的血壓變化",
      SharetoWeChatfriends:"分享至微信好友",

      Setting:"設置",

      //主页面
      DadsBloodPressure:"用戶1 測的血壓",
      MothersBloodPressure:"用戶2 測的血壓",
      UserFBloodPressure:"1 測的血壓",
      UserMBloodPressure:"2 測的血壓",
      Findmore:"發現更多",
      ResultsOfNormalBloodPressure:"正常血壓結果(次)",
      HighBloodPressureResults:"偏高血壓結果(次)",
      HighVoltageHighestValue:"高壓最高值(mmHg)",
      LowVoltageHighestValue:"低壓最高值(mmHg)",
      BloodPressureMean:"血壓平均值(mmHg)",
      MeanValueOfPulsePressure:"脈壓平均值(mmHg)",
      Normal:" 正常 ",
      High:" 偏高 ",
      Low:" 偏低 ",
      BloodPressureOutcomeDetails:"血壓結果詳情",
      AccordingToWHO:"根據WHO世界衛生組織血壓標準評定您本次測量為：",
      SevereHypertension:"重度高血壓",
      ModerateHypertension:"中度高血壓",
      MildHypertension:"輕度高血壓",
      NormalPartialHypertension:"正常偏高血壓",
      NormalBloodPressure:"正常血壓",
      IdealBloodPressure:"理想血壓",
      HighPressure:"高壓",
      LowPressure:"低壓",
      HeartRate:"心率",
      TimesPerMinute:"次/分鐘",
      InterpretationOfBloodPressureResults:"血壓結果解讀",
      HowDoYouFeelBeforeYouMeasure:"【心情】:測量前的心情感覺如何？",
      Good:"好",
      Commonly:"一般",
      Bad:"不好",
      TakingAntihypertensiveDrugsWithin2Hours:"【服藥】：2小時內服用過降壓藥嗎？",
      Yes:"有",
      No:"没有",
      LoadLatestMeasurementRecord:"加載最新測量記錄",
      LoadingHistoryRecord:"加載歷史測量記錄",
      Loading:"加載中",

      nian:"年",
      yue:"月",
      ri:"日",
    },
    "zh-HK":{
      //繁体中文（香港）
      //无用
      OpenAJK:"打開愛家康",
      AboutBloodPressure:"关于血压计",

      //设置页内容
      重命名:"重命名",
      设备共享:"设备共享",
      检查固件更新:"检查固件更新",
      解除连接:"解除连接",
      更多:"更多",
      编辑:"编辑",
      完成:"完成",
      RevokeTheTermsOfUseAndPrivacyPolicyAuthorization:"撤销\"使用条款和隐私政策\"授权",


      DearRemind:"寶貝提醒",
      AccessWeChat:"接入微信",
      DeviceInformation:"设备信息",
      Help:"帮助",
      UniversalSettings:"通用设置",
      BootScreen:"血压计开机画面",
      AgreementAndPolicy:"服务协议和隐私政策",
      ServiceAgreement:"服务协议",
      PrivacyPolicy:"隐私政策",
      MeasurementResultsVoiceBroadcast: "測量結果語音播報",
      BatteryPower:"電池電量",
      SerialNumber:"序列號",
      FirmwareVersion:"固件版本號",
      PluginVersion:"插件版本",

      BPUsingInstructions:"使用說明",
      BPFaq:"常見問題",

      WhenTheBloodPressureMonitorOn:"當血壓計開機時，將收到默認留言",
      MON:"周一",
      TUE:"周二",
      WED:"周三",
      THU:"周四",
      FRI:"周五",
      SAT:"周六",
      SUN:"周日",
      MomAndDadRemind:"爸爸媽媽，記得堅持測血壓！",

      iHealthBloodPressureMonitor:" iHealth智控血壓",
      ShareWeChat:"分享血壓計二維碼給微信親友，方便親友實时關注您的血壓變化",
      SharetoWeChatfriends:"分享至微信好友",

      Setting:"設置",

      //主页面
      DadsBloodPressure:"用戶1 測的血壓",
      MothersBloodPressure:"用戶2 測的血壓",
      UserFBloodPressure:"1 測的血壓",
      UserMBloodPressure:"2 測的血壓",
      Findmore:"發現更多",
      ResultsOfNormalBloodPressure:"正常血壓結果(次)",
      HighBloodPressureResults:"偏高血壓結果(次)",
      HighVoltageHighestValue:"高壓最高值(mmHg)",
      LowVoltageHighestValue:"低壓最高值(mmHg)",
      BloodPressureMean:"血壓平均值(mmHg)",
      MeanValueOfPulsePressure:"脈壓平均值(mmHg)",
      Normal:" 正常 ",
      High:" 偏高 ",
      Low:" 偏低 ",
      BloodPressureOutcomeDetails:"血壓結果詳情",
      AccordingToWHO:"根據WHO世界衛生組織血壓標準評定您本次測量為：",
      SevereHypertension:"重度高血壓",
      ModerateHypertension:"中度高血壓",
      MildHypertension:"輕度高血壓",
      NormalPartialHypertension:"正常偏高血壓",
      NormalBloodPressure:"正常血壓",
      IdealBloodPressure:"理想血壓",
      HighPressure:"高壓",
      LowPressure:"低壓",
      HeartRate:"心率",
      TimesPerMinute:"次/分鐘",
      InterpretationOfBloodPressureResults:"血壓結果解讀",
      HowDoYouFeelBeforeYouMeasure:"【心情】:測量前的心情感覺如何？",
      Good:"好",
      Commonly:"一般",
      Bad:"不好",
      TakingAntihypertensiveDrugsWithin2Hours:"【服藥】：2小時內服用過降壓藥嗎？",
      Yes:"有",
      No:"没有",
      LoadLatestMeasurementRecord:"加載最新測量記錄",
      LoadingHistoryRecord:"加載歷史測量記錄",
      Loading:"加載中",

      nian:"年",
      yue:"月",
      ri:"日",
    },
    "zh-TW":{
      //繁体中文（台湾）
      //无用
      OpenAJK:"打開愛家康",
      AboutBloodPressure:"关于血压计",

      //设置页内容
      重命名:"重命名",
      设备共享:"设备共享",
      检查固件更新:"检查固件更新",
      解除连接:"解除连接",
      更多:"更多",
      编辑:"编辑",
      完成:"完成",
      RevokeTheTermsOfUseAndPrivacyPolicyAuthorization:"撤销\"使用条款和隐私政策\"授权",


      DearRemind:"寶貝提醒",
      AccessWeChat:"接入微信",
      DeviceInformation:"设备信息",
      Help:"帮助",
      UniversalSettings:"通用设置",
      AgreementAndPolicy:"服务协议和隐私政策",
      ServiceAgreement:"服务协议",
      PrivacyPolicy:"隐私政策",
      BootScreen:"血压计开机画面",

      MeasurementResultsVoiceBroadcast: "測量結果語音播報",
      BatteryPower:"電池電量",
      SerialNumber:"序列號",
      FirmwareVersion:"固件版本號",
      PluginVersion:"插件版本",

      BPUsingInstructions:"使用說明",
      BPFaq:"常見問題",

      WhenTheBloodPressureMonitorOn:"當血壓計開機時，將收到默認留言",
      MON:"周一",
      TUE:"周二",
      WED:"周三",
      THU:"周四",
      FRI:"周五",
      SAT:"周六",
      SUN:"周日",
      MomAndDadRemind:"爸爸媽媽，記得堅持測血壓！",

      iHealthBloodPressureMonitor:" iHealth智控血壓",
      ShareWeChat:"分享血壓計二維碼給微信親友，方便親友實时關注您的血壓變化",
      SharetoWeChatfriends:"分享至微信好友",

      Setting:"設置",
      
      //主页面
      DadsBloodPressure:"用戶1 測的血壓",
      MothersBloodPressure:"用戶2 測的血壓",
      UserFBloodPressure:"1 測的血壓",
      UserMBloodPressure:"2 測的血壓",
      Findmore:"發現更多",
      ResultsOfNormalBloodPressure:"正常血壓結果(次)",
      HighBloodPressureResults:"偏高血壓結果(次)",
      HighVoltageHighestValue:"高壓最高值(mmHg)",
      LowVoltageHighestValue:"低壓最高值(mmHg)",
      BloodPressureMean:"血壓平均值(mmHg)",
      MeanValueOfPulsePressure:"脈壓平均值(mmHg)",
      Normal:" 正常 ",
      High:" 偏高 ",
      Low:" 偏低 ",
      BloodPressureOutcomeDetails:"血壓結果詳情",
      AccordingToWHO:"根據WHO世界衛生組織血壓標準評定您本次測量為：",
      SevereHypertension:"重度高血壓",
      ModerateHypertension:"中度高血壓",
      MildHypertension:"輕度高血壓",
      NormalPartialHypertension:"正常偏高血壓",
      NormalBloodPressure:"正常血壓",
      IdealBloodPressure:"理想血壓",
      HighPressure:"高壓",
      LowPressure:"低壓",
      HeartRate:"心率",
      TimesPerMinute:"次/分鐘",
      InterpretationOfBloodPressureResults:"血壓結果解讀",
      HowDoYouFeelBeforeYouMeasure:"【心情】:測量前的心情感覺如何？",
      Good:"好",
      Commonly:"一般",
      Bad:"不好",
      TakingAntihypertensiveDrugsWithin2Hours:"【服藥】：2小時內服用過降壓藥嗎？",
      Yes:"有",
      No:"没有",
      LoadLatestMeasurementRecord:"加載最新測量記錄",
      LoadingHistoryRecord:"加載歷史測量記錄",
      Loading:"加載中",

      nian:"年",
      yue:"月",
      ri:"日",
    }
  });

  module.exports = strings;
